
import streamlit as st
import pandas as pd
import subprocess
import os
import sys

# --- CONFIGURAÇÃO DA PÁGINA WEB ---
st.set_page_config(
    page_title="ASSET | Arthroscopy Automated Assessment",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CONFIGURAÇÃO VISUAL (CSS para manter a tua identidade visual) ---
st.markdown("""
    <style>
    .main { background-color: #F5F7FA; }
    h1 { color: #1A237E; font-family: 'Segoe UI', sans-serif; font-weight: bold; }
    .stButton>button {
        background-color: #00B8D4;
        color: white;
        font-weight: bold;
        border-radius: 30px;
        height: 50px;
        width: 100%;
        border: none;
    }
    .stButton>button:hover { background-color: #0097A7; color: white; }
    </style>
""", unsafe_allow_html=True)

# Ficheiros de controlo internos
LOG_FILE = "resultados_asset.txt"
MASTER_SCRIPT = "ASSET_MASTER_v6.py"

# --- SIDEBAR (Menu Lateral) ---
with st.sidebar:
    st.markdown("<h2 style='color: white; text-align: center;'>ASSET<br>SYSTEM</h2>", unsafe_allow_html=True)
    st.write("---")
    
    # 1. Carregador de Vídeo (Substitui o filedialog)
    uploaded_file = st.file_uploader(
        "📁 LOAD VIDEO", 
        type=["mp4", "avi", "mov", "mkv", "m4v", "mpg"],
        help="Selecione o vídeo de artroscopia para análise."
    )
    
    st.write("---")
    st.markdown("<b style='color: #BBDEFB;'>SELECT METRICS:</b>", unsafe_allow_html=True)
    
    # Lista de métricas originais
    metrics_options = [
        "Safety", "Field of View", "Camera Dexterity", 
        "Instrument Dexterity", "Bi-Manual Dexterity", 
        "Flow of Procedure", "Quality of Procedure", "Autonomy"
    ]
    
    # Checkboxes dinâmicos (Substitui os BooleanVar do customtkinter)
    selected_metrics = []
    for metric in metrics_options:
        if st.checkbox(metric, value=True):
            selected_metrics.append(metric)
            
    st.write("---")
    # Estado do vídeo na Sidebar
    if uploaded_file:
        st.success(f"CONNECTED:\n{uploaded_file.name}")
    else:
        st.info("No video selected")

# --- MAIN CONTENT (Conteúdo Principal) ---
st.title("Arthroscopy Surgical Assessment")
st.caption("Unified automated evaluation system (Safety, Dexterity, FOV, Flow & Quality).")

# Criar um "Card" visual para a execução
with st.container():
    st.markdown("### Ready for Custom Diagnostic")
    
    # Botão de Execução
    if st.button("START EVALUATION"):
        if not uploaded_file:
            st.error("Medical Alert: No surgical video has been loaded!")
            
        elif not selected_metrics:
            st.error("Selection Error: Please select at least one metric to analyze!")
            
        elif not os.path.exists(MASTER_SCRIPT):
            st.error(f"Error: Master script not found: {MASTER_SCRIPT}")
            
        else:
            # Remover log antigo se existir
            if os.path.exists(LOG_FILE):
                os.remove(LOG_FILE)
                
            # Estado: A Processar
            status_warning = st.warning("Processing... please wait. Running Analysis.")
            
            try:
                # 1. Gravar temporariamente o vídeo carregado no servidor para o Master Script o conseguir ler
                temp_video_path = f"temp_{uploaded_file.name}"
                with open(temp_video_path, "wb") as f:
                    f.write(uploaded_file.getbuffer())
                
                # 2. Configurar os argumentos para o subprocess
                args = [sys.executable, MASTER_SCRIPT, temp_video_path] + selected_metrics
                
                # Executa o teu script mestre e espera que termine
                subprocess.run(args, check=True)
                
                # Limpar aviso de espera
                status_warning.empty()
                
                # 3. Processar o ficheiro TXT gerado pelo teu script mestre
                if not os.path.exists(LOG_FILE):
                    st.error("Data Error: No results were generated by the Master script.")
                else:
                    resultados = []
                    contagem = 0
                    
                    with open(LOG_FILE, "r") as f:
                        for linha in f:
                            if ":" in linha:
                                partes = linha.strip().split(":")
                                if len(partes) < 2: 
                                    continue
                                
                                metrica = partes[0].strip()
                                try:
                                    nota_val = float(partes[1])
                                    
                                    # Filtra apenas o que o utilizador selecionou nas checkboxes
                                    if metrica in selected_metrics:
                                        resultados.append({
                                            "Metric": metrica,
                                            "Score": int(nota_val),
                                            "Video": uploaded_file.name
                                        })
                                        contagem += 1
                                except ValueError:
                                    continue
                    
                    # Criar o DataFrame e remover duplicados
                    df = pd.DataFrame(resultados).drop_duplicates(subset=['Metric'], keep='last')
                    
                    if df.empty:
                        st.warning("No matching metrics data found in the results file.")
                    else:
                        st.success(f"Analysis Cycle Completed. Metrics processed: {contagem}")
                        
                        # Mostra a tabela de resultados diretamente na página web
                        st.subheader("Clinical Evaluation Results")
                        st.dataframe(df, use_container_width=True)
                        
                        # 4. GERAR EXCEL PARA DOWNLOAD (Substitui a gravação direta no disco C:)
                        # Extrair o nome do aluno tal como tinhas na lógica original
                        nome_base = uploaded_file.name.split('.')[0]
                        nome_aluno = nome_base.replace('_RAFT_ANALISE', '')
                        nome_arquivo_excel = f"REPORT_ASSET_{nome_aluno}.xlsx"
                        
                        # Converter o dataframe em bytes de Excel recorrendo ao openpyxl/pandas
                        import io
                        buffer = io.BytesIO()
                        with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                            df.to_excel(writer, index=False, sheet_name='Assessment')
                        
                        # Botão nativo da Web para o utilizador descarregar o relatório
                        st.download_button(
                            label="📥 DOWNLOAD CLINICAL REPORT (EXCEL)",
                            data=buffer.getvalue(),
                            file_name=nome_arquivo_excel,
                            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                        )
                        
                # Limpeza: apagar o vídeo temporário do servidor
                if os.path.exists(temp_video_path):
                    os.remove(temp_video_path)
                    
            except Exception as e:
                st.error(f"System Failure: Error during processing: {e}")

    # Mensagem de rodapé caso o botão não tenha sido clicado
    if not st.session_state.get('FormSubmitter:deft_form-Submit', False):
        st.info("System Idle - Select a video and click 'START EVALUATION'")